color0 #474551
color1 #ffb4ab
color2 #c4c0ff
color3 #c6c3e9
color4 #feacef
color5 #c4c0ff
color6 #c6c3e9
color7 #e5e1e9
color8 #928f9c
color9 #ffb4ab
color10 #c4c0ff
color11 #c6c3e9
color12 #feacef
color13 #c4c0ff
color14 #c6c3e9
color15 #e5e1e9

cursor                #e5e1e9
cursor_text_color     #131318
background            #131318
foreground            #e5e1e9
selection_foreground  #c8c5d2
selection_background  #474551
active_border_color   #c4c0ff
inactive_border_color #474551
url_color             #c4c0ff

active_tab_foreground   #292473
active_tab_background   #c4c0ff
inactive_tab_foreground #c8c5d2
inactive_tab_background #474551
cursor_trail_color      #c8c5d2
