#!/usr/bin/env python3
"""Generate the AUR PKGBUILD depends/optdepends arrays from .module.toml.

Single source of truth (§5.7): adding a config app only touches configs/ (its
.manifest declares packages); this script regenerates the PKGBUILD's depends.
Run `python3 nyxuri/packaging/gen-deps.py --update` to rewrite the generated
blocks, or without --update to print them.

  depends    = deployable apps' packages ∪ CORE_DEPS ∪ AUR_DEPS
  optdepends = manifest-only apps' packages (optional installable apps)
"""

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PKGBUILD = Path(__file__).resolve().parent / "PKGBUILD"

_BEGIN = "# >>> depends (auto-generated by nyxuri/packaging/gen-deps.py) >>>"
_END = "# <<< depends <<<"
_OBEGIN = "# >>> optdepends (auto-generated by nyxuri/packaging/gen-deps.py) >>>"
_OEND = "# <<< optdepends <<<"


def compute_depends(repo_root: Path):
    """Return (depends: list[str], optdepends: list[tuple[pkg, label]])).

    Deployable apps' packages feed `depends`; manifest-only apps (optional
    installable, e.g. nautilus/missioncenter/fcitx5-rime) feed `optdepends`.
    Base system deps not tied to an app come from CORE_DEPS/AUR_DEPS.
    """
    sys.path.insert(0, str(repo_root))
    from nyxuri.deploy.manifest import discover_manifest_apps
    from nyxuri.constants import AUR_DEPS, CORE_DEPS

    depends = set()
    optdepends = []
    for _name, m in discover_manifest_apps():
        # Axis B (optional, .optional-apps.toml) wins → optdepends, even if the
        # app also ships a config dir (optional + config coexist, §2).
        if m.is_optional:
            for pkg in list(m.packages_repo) + list(m.packages_aur):
                optdepends.append((pkg, m.label))
        elif m.is_deployable:
            depends.update(m.packages_repo)
            depends.update(m.packages_aur)

    depends.update(CORE_DEPS)
    depends.update(AUR_DEPS)
    return sorted(depends), optdepends


def _render(depends, optdepends):
    dep_block = _BEGIN + "\ndepends=(\n" + "".join(f"  '{p}'\n" for p in depends) + ")\n" + _END
    if optdepends:
        opt_block = _OBEGIN + "\noptdepends=(\n" + "".join(f"  '{p}: {lbl}'\n" for p, lbl in optdepends) + ")\n" + _OEND
    else:
        opt_block = _OBEGIN + "\noptdepends=(\n)\n" + _OEND
    return dep_block + "\n" + opt_block


def update_pkgbuild(depends, optdepends) -> bool:
    """Rewrite the generated blocks in PKGBUILD. Returns True if changed."""
    if not PKGBUILD.is_file():
        return False
    text = PKGBUILD.read_text(encoding="utf-8")
    new = _render(depends, optdepends)
    import re
    pattern = re.compile(re.escape(_BEGIN) + r".*?" + re.escape(_OEND), re.DOTALL)
    if not pattern.search(text):
        return False
    out = pattern.sub(new.rstrip("\n"), text).rstrip("\n") + "\n"
    if out == text:
        return False
    PKGBUILD.write_text(out, encoding="utf-8")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate AUR depends from .module.toml")
    ap.add_argument("--update", action="store_true", help="rewrite PKGBUILD in place")
    args = ap.parse_args()

    depends, optdepends = compute_depends(REPO_ROOT)
    if args.update:
        changed = update_pkgbuild(depends, optdepends)
        print("PKGBUILD " + ("updated" if changed else "unchanged"))
        return 0
    print(_render(depends, optdepends))
    return 0


if __name__ == "__main__":
    sys.exit(main())
